### ISSUE TITLE
allow for own template of events-detail modal

### ISSUE THREAD

**Issue by vinstah** [stormseed/quasar-calendar#19]
I have been using the calendar as a way to show jobs rather than events and don't really have a need for guests, can I use the same Google calendar API but change the modal layout to represent my info

**Comment by sirbeagle** [comment]
I did write some basic functionality to allow for this but it is super untested so far. I'll move this up on the priority list.

The idea would be that you could just copy the existing `CalendarEventDetail` component, customize it as you need, drop it somewhere where `$refs` can see it and then pass in the reference name as a parameter. Once I have the code fully tested I'll write up some docs on how to do it.
