### ISSUE TITLE
Unknown custom element: <calendar-month>

### ISSUE THREAD

**Issue by BartekPacocha** [stormseed/quasar-calendar#26]
Hi, I have a problem when i try to use quasar-calendar. After install via npm and trying to use it in my code i got error:

Unknown custom element: <calendar-month> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by sirbeagle** [comment]
@BartekPacocha I'd have to see more of your code to know what's happening. When you're using vue you have to be sure to `import` the components you want to use. Check out the [source for the demo page](https://github.com/stormseed/quasar-calendar-demo/blob/master/src/pages/index.vue) to see how I imported the main calendar components and see if that helps?

**Comment by ChukkaAshok** [comment]
Hi, I'm also getting same problem when i trying to use quasar-calendar. Any solution?
**Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.**
Please update me if any solution asap. Thanks.

**Comment by ChukkaAshok** [comment]
**@sirbeagle** I have resolve the problem  thanks for the link **[source for the demo page](https://github.com/stormseed/quasar-calendar-demo/blob/master/src/pages/index.vue)** it is very use full for every one.  Thanks.
