### ISSUE TITLE
[Vue warn]: Unknown custom element: <calendar> - did you register the component correctly?

### ISSUE THREAD

**Issue by KnowledgeGarden** [stormseed/quasar-calendar#30]
That's the message I get if I follow the instructions on the ReadMe:
<pre>
< template>
  < q-page>
    < calendar />
  < /q-page>
< /template>
<script>
import { Calendar } from 'quasar-calendar'
</script>
</pre>
quasar-calendar is in node_modules

There was this compiler warning (not  crash)
 warning  in ./src/pages/Calendar.vue
17:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader!../../node_modules/vue-loader/lib/selector?type=script&index=0!./Calendar.vue'

This is not a Q-<widget> to put in quasar.config.js, and there are no instructions to create a Vue component.
I must have missed something.

**Comment by KnowledgeGarden** [comment]
Perhaps it would be useful to include the demo code in an /example folder in /src

**Comment by KnowledgeGarden** [comment]
The installation console said this: npm WARN quasar-calendar@0.3.0 requires a peer of quasar-framework@^0.16.0 but none is installed. You must install peer dependencies yourself.
uninstalling and installing install-peers then reinstalling calendar did not catch the peer dependency.

As it turns out, just installing quasar-framework failed to complete the install; a missing file.

**Comment by KnowledgeGarden** [comment]
Here is a sequence: install quasar-framework, then install quasar-calendar. Here's the trace:
+ quasar-framework@0.17.5

npm install --save quasar-calendar
npm WARN quasar-calendar@0.3.0 requires a peer of quasar-framework@^0.16.0 but none is installed. You must install peer dependencies yourself.
+ quasar-calendar@0.3.0

**Comment by dnasir** [comment]
Did you add the necessary component registration in the component you're using the calendar on?

e.g.

```vue
<template>
  <q-page>
    <calendar />
  </q-page>
</template>
<script>
import { Calendar } from 'quasar-calendar';

export default {
  components: {
    Calendar
  }
}
</script>
```

**Comment by KnowledgeGarden** [comment]
When you go through all of the steps, and you install quasar-calendar, how do you deal with this npm message?
npm WARN quasar-calendar@0.3.0 requires a peer of quasar-framework@^0.16.0 but none is installed. You must install peer dependencies yourself.

**Comment by dnasir** [comment]
If you've already installed quasar, then you can simply ignore this
warning. It's working fine for me.

**Comment by KnowledgeGarden** [comment]
It is for me as well. Thanks!
