### ISSUE TITLE
[Feature Request] Current time indicator

### ISSUE THREAD

**Issue by dnasir** [stormseed/quasar-calendar#31]
I'm building a simple appointment scheduler, and a time indicator much like the one found in Google Calendar would be nice to have. It should be displayed when the calendar is in week or day view.

![image](https://user-images.githubusercontent.com/1737051/43860918-dfa84aea-9b5d-11e8-87ee-0579054582bf.png)

**Comment by sirbeagle** [comment]
Yup, makes sense - will add it to the to do list.

**Comment by sirbeagle** [comment]
The code for this is done and will be in the next release coming shortly.
