### ISSUE TITLE
[Feature Request] Limit start and end time for calendar-multi-day

### ISSUE THREAD

**Issue by danielcomcom** [stormseed/quasar-calendar#32]
It would be awesome if I could limit the start and end times of this view to only business hours where events would most likely be scheduled. Maybe this is already possible somehow?

**Comment by sirbeagle** [comment]
I don't know if I would want to restrict the times that are shown, but would shading in business hours by passing in a `business_day_start` and `business_day_end` times be an option?

**Comment by danielcomcom** [comment]
Attached is a screenshot of the problem that I am running into. In short, every time you would want to see anything useful you have to scroll through 1am to 8am. 
![screenshot_143](https://user-images.githubusercontent.com/13260904/44059662-00111b98-9f07-11e8-91e8-9b4993fe82c8.png)
Maybe there is some other way of working around this, I'm totally open to any ideas!

**Comment by danielcomcom** [comment]
The basic use case is a way to visualize where openings might be to schedule an event such as a onsite visit.

**Comment by danielcomcom** [comment]
I guess starting the default focus to a normal part of the day is what I'm getting at, here's a screen shot from gmail, they do this.
![screenshot_144](https://user-images.githubusercontent.com/13260904/44059861-95e91300-9f07-11e8-9e15-61aa5bd632e5.png)

**Comment by sirbeagle** [comment]
Yeah, what you're saying makes a ton of sense. I was thinking of adding the "work hours" shading at some point, but having the calendar jump to a reasonable start time during the day would make sense as well. Let me think about how best to implement both, but I'll put in some solution shortly with the next version.

**Comment by danielcomcom** [comment]
Awesome! And by the way I think it’s super cool that you’ve made a module
for the quasar framework!

Sent from Daniel's iPhone

On Aug 13, 2018, at 2:53 PM, Chris Benjamin <notifications@github.com>
wrote:

Yeah, what you're saying makes a ton of sense. I was thinking of adding the
"work hours" shading at some point, but having the calendar jump to a
reasonable start time during the day would make sense as well. Let me think
about how best to implement both, but I'll put in some solution shortly
with the next version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stormseed/quasar-calendar/issues/32#issuecomment-412678021>,
or mute the thread

**Comment by kdmon** [comment]
Assuming your multi-day-calendar has an id of 'calendar', a temporary workaround is to set scrolltop in the mounted method of your view component, like this:

```javascript
// Scroll to 7am
let elem = document.getElementById('calendar').getElementsByClassName('scroll')[0]
elem.scrollTop = 560
```

**Comment by sirbeagle** [comment]
I think I added a feature in v0.3.1 that addressed this. I'll close this out but please re-open if you feel it hasn't been.
