### ISSUE TITLE
Displaying Multi-Day Events

### ISSUE THREAD

**Issue by wooliet** [stormseed/quasar-calendar#36]
I am using `<calendar-month>` and have an `events-array` property set to the data we want to 
display.  

Events that start and end on the same day seem to display fine. However, display of events that span  multiple days does not seem to work with the data I'm providing.

One of the objects in `events-array` contains the data:
```
{
  start:  { dateTime: "2018-09-24T14:00:00.000Z" },
  end: { dateTime: "2018-09-25T20:00:00.000Z" }
}
```

It _only_ shows a entry on the calendar for the start day. It does _not_ show that the event spans across two days.

Is there something else I need to be doing? Is what I'm doing now wrong in some way?

**Comment by wooliet** [comment]
I see that using `date` instead of `dateTime` within the start and end objects shows multiple days. But if I remove `dateTime`, I no longer get the single day entries.

I would like to have a start and end time associated with an event that spans multiple days. Does this mean I need to include both a `date` _and_ a `dateTime` property with start & end for every event?

**Comment by sirbeagle** [comment]
I'll have to test that - I have a feeling I didn't account for that scenario properly.
